# dj-chuy Docker Compose

services:
  db:
    build:
      context: ./server/db/
      dockerfile: db.Dockerfile
    container_name: dj-chuy-db
    environment:
      - POSTGRES_DB=${DB_NAME:-dj-chuy}
      - POSTGRES_USER=${DB_OWNER_ADMIN:-chuy}
      - POSTGRES_PASSWORD=${DB_OWNER_PWORD:-password}
      # Pass these variables explicitly for the init script
      - DB_NAME=${DB_NAME:-dj-chuy}
      - DB_OWNER_ADMIN=${DB_OWNER_ADMIN:-chuy}
      - DB_OWNER_PWORD=${DB_OWNER_PWORD:-password}
      - TZ=UTC
    ports:
      - "5432:5432"
    networks:
      - dj-chuy-network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${DB_OWNER_ADMIN:-chuy} -d ${DB_NAME:-dj-chuy}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s

  api:
    build:
      context: ./server/api/
      dockerfile: api.Dockerfile
    container_name: dj-chuy-api
    environment:
      - DB_NAME=${DB_NAME:-dj-chuy}
      - DB_HOST=dj-chuy-db
      - DB_OWNER_ADMIN=${DB_OWNER_ADMIN:-chuy}
      - DB_OWNER_PWORD=${DB_OWNER_PWORD:-password}
      - PYTHONDONTWRITEBYTECODE=1  # Prevents Python from writing pyc files to disc
      - PYTHONUNBUFFERED=1  # Prevents Python from buffering stdout and stderr
    ports:
      - "8000:8000"
    volumes:
      - ./server/api:/app
    depends_on:
      - db
    networks:
      - dj-chuy-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s

  # dj-chuy-hub:
  #   build:
  #     context: ./core
  #     dockerfile: hub.Dockerfile
  #   container_name: dj-chuy-hub
  #   volumes:
  #     - ./core:/app
  #     - /app/node_modules  # This prevents the mounted volume from overwriting node_modules
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - dj-chuy-network

networks:
  dj-chuy-network:
    name: dj-chuy-network
    driver: bridge

volumes:
  postgres_data:
    name: dj-chuy-postgres-data
